# Generated by Django 3.2.7 on 2021-10-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thep', '0003_remove_student_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='place',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
